#!/usr/bin/env python3
"""Profile derived VCDB tables and write machine- and human-readable summaries."""

from __future__ import annotations

import csv
import json
from collections import Counter, defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DERIVED = ROOT / "data" / "derived"


def split_values(value: object) -> list[str]:
    return [item for item in str(value or "").split(";") if item]


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as source:
        return list(csv.DictReader(source))


def crosstab(rows: list[dict[str, str]], list_column: str, dimension: str) -> dict[str, dict[str, int]]:
    table: dict[str, Counter[str]] = defaultdict(Counter)
    for row in rows:
        for variety in split_values(row.get(list_column)):
            for value in split_values(row.get(dimension)):
                table[variety][value] += 1
    return {variety: dict(sorted(counts.items())) for variety, counts in sorted(table.items())}


def samples(rows: list[dict[str, str]], variety: str, column: str) -> list[str]:
    result = []
    for row in rows:
        summary = row.get("summary", "").replace("\n", " ").strip()
        if variety in split_values(row.get(column)) and summary:
            result.append(summary)
        if len(result) == 3:
            break
    return result


def markdown_table(counter: Counter[str]) -> list[str]:
    return (["| Variety | Incidents |", "| --- | ---: |"] +
            [f"| {name} | {count:,} |" for name, count in counter.most_common()])


def main() -> None:
    incidents_path, narratives_path = DERIVED / "incidents.csv", DERIVED / "narratives.csv"
    if not incidents_path.exists() or not narratives_path.exists():
        raise FileNotFoundError("Missing derived CSVs; run pipeline/build.py first.")
    incidents, narratives = read_csv(incidents_path), read_csv(narratives_path)
    error_counts = Counter(item for row in incidents for item in split_values(row.get("error_varieties")))
    social_counts = Counter(item for row in incidents for item in split_values(row.get("social_varieties")))
    combined = []
    for row in incidents:
        copy = dict(row)
        copy["varieties"] = ";".join(dict.fromkeys(split_values(row.get("error_varieties")) + split_values(row.get("social_varieties"))))
        combined.append(copy)
    discovery: dict[str, Counter[str]] = defaultdict(Counter)
    for row in incidents:
        for category in split_values(row.get("discovery_categories")) or ["(none recorded)"]:
            for variety in split_values(row.get("error_varieties")):
                discovery[category][variety] += 1

    stats = {
        "counts": {
            "incidents": len(incidents),
            "incidents_with_summary": sum(row.get("has_summary", "").lower() == "true" for row in incidents),
            "action_error_incidents": sum(row.get("action_error", "").lower() == "true" for row in incidents),
            "action_social_incidents": sum(row.get("action_social", "").lower() == "true" for row in incidents),
            "error_varieties": dict(sorted(error_counts.items())),
            "social_varieties": dict(sorted(social_counts.items())),
        },
        "cross_tabs": {
            "variety_by_year": crosstab(combined, "varieties", "year"),
            "variety_by_industry": crosstab(combined, "varieties", "victim_industry_naics2"),
            "variety_by_asset": crosstab(combined, "varieties", "asset_varieties"),
            "discovery_category_by_error_variety": {method: dict(sorted(counts.items()))
                                                    for method, counts in sorted(discovery.items())},
        },
    }
    (DERIVED / "stats.json").write_text(json.dumps(stats, indent=2, sort_keys=True) + "\n")
    lines = ["# VCDB profile", "", "Generated by `python3 pipeline/profile.py` from the local VCDB combined dataset.", "",
             "## Headline counts", "", f"- Incidents: {len(incidents):,}",
             f"- Incidents with a non-empty summary: {stats['counts']['incidents_with_summary']:,}",
             f"- Incidents with `action.error`: {stats['counts']['action_error_incidents']:,}",
             f"- Incidents with `action.social`: {stats['counts']['action_social_incidents']:,}", "",
             "## Error varieties", "", *markdown_table(error_counts), "", "## Social varieties", "", *markdown_table(social_counts), "",
             "## Sample narratives", "", "Samples are source summaries, selected deterministically in input order; empty summaries are omitted.", ""]
    for column, counts, heading in (("error_varieties", error_counts, "Error"), ("social_varieties", social_counts, "Social")):
        for variety in counts:
            lines.extend([f"### {heading}: {variety}", ""])
            examples = samples(narratives, variety, column)
            lines.extend([f"{index}. {example}" for index, example in enumerate(examples, 1)] or ["No non-empty source summaries available."])
            lines.append("")
    (DERIVED / "PROFILE.md").write_text("\n".join(lines))
    print(f"Wrote {DERIVED.relative_to(ROOT) / 'stats.json'} and {DERIVED.relative_to(ROOT) / 'PROFILE.md'}")


if __name__ == "__main__":
    main()
